### ISSUE TITLE
Libreoffice menus broken

### ISSUE THREAD

**Issue by ghost** [dirruk1/gnome-breeze#12]
Menus in libreoffice are broken but are fine in other gtk applications.

Libreoffice:

![snapshot2-libre](https://cloud.githubusercontent.com/assets/850766/8632405/cc0666c4-2767-11e5-97c5-a72d4cf28d74.png)

Firefox and other gtk applications (ignore the fading, only appears in screenshot):

![snapshot3-ff](https://cloud.githubusercontent.com/assets/850766/8632414/1867d1b0-2768-11e5-8b17-fdc9ff0bf8d5.png)

**Comment by dirruk1** [comment]
This is libreoffice-kde https://bugs.kde.org/show_bug.cgi?id=348513. It's not the gtk theme

**Comment by ghost** [comment]
Thanks, removing libreoffice-kde and having libreoffice emulate the gtk theme fixes it.

Please close this issue.
