### ISSUE TITLE
Text in tool-tips hard to read

### ISSUE THREAD

**Issue by FiveYellowMice** [dirruk1/gnome-breeze#14]
One example is GIMP.
![snapshot4](https://cloud.githubusercontent.com/assets/9077203/8765798/3bda5a72-2e62-11e5-9f67-e7b8c112d19f.png)
The text background and text itself are both white, therefore unreadable.

**Comment by Steinhagen** [comment]
You can find the answer to your problem here:
https://github.com/dirruk1/gnome-breeze/issues/7
