### ISSUE TITLE
Add support to "Breeze Dark" color scheme

### ISSUE THREAD

**Issue by sl1pkn07** [dirruk1/gnome-breeze#2]
Hi

is posible add support to "Breeze Dark" color scheme?

greetings

**Comment by dirruk1** [comment]
for gtk-3 there already is a first dark version, if you want to test it rename the file gtk-dark.css to gtk.css

**Comment by sl1pkn07** [comment]
dark version working with GTK3 if add

```
gtk-application-prefer-dark-theme=true
```

to $HOME/.config/gtk-3.0/settings.ini

but not in GTK2 with the same option in $HOME/.gtkrc-2.0

**Comment by ghost** [comment]
GTK 2 doesn't support dark theme variants. We could eventually create a separate GTK 2 theme for the dark color scheme, but the focus is currently on completing the theme itself.

**Comment by ghost** [comment]
So, dirruk1 went ahead and created a dark variant for GTK 2 along with the existing GTK 3 support. I'd say this is resolved.
