### ISSUE TITLE
Breeze-gtk makes all apps black

### ISSUE THREAD

**Issue by stevenroose** [dirruk1/gnome-breeze#21]
I don't know for sure if it is the team or my pc, but I first picked Breeze-dark-gtk and all my GTK apps became unreadibly black, so I switched to Breeze-gtk and rebooted, but still most apps are black.

F.e. SmartGit
![](https://i.imgur.com/k9RBxxc.png)

**Comment by stevenroose** [comment]
Most problems are with white buttons that keep the white text.

**Comment by dirruk1** [comment]
Do you have "apply colors to non-qt apps" enabled in system settings>color>options ?

**Comment by stevenroose** [comment]
Yes. It's default in Fedora it seems

**Comment by dirruk1** [comment]
yes it is default but you should disable it, it fixes most of the problems

**Comment by stevenroose** [comment]
K thanks!

**Comment by mrueg** [comment]
@dirruk1 Could you add a section to the readme file regarding "apply colors to non-qt apps"?

**Comment by ghost** [comment]
As I'm not certain we can actually resolve this issue within the theme itself, I think this issue should be kicked up the stack. In addition to fact that there's a simple workaround, I think that's reason enough to close this report.
