### ISSUE TITLE
Incorrect scrollbar colours in Firefox

### ISSUE THREAD

**Issue by FLHerne** [dirruk1/gnome-breeze#26]
In Firefox (but no other gtk2 applications I've tried), the scrollbars are drawn in slightly-but-jarringly incorrect colours.

With the Breeze colourscheme, the area is RGB #D6D8DB, the slot is #BDC3C7 and the slider #74757A. The expected colours as used by other applications are #EFF0F1, #B7B6BB, #74777B respectively.

Screenshot - the background of planetkde.org is the expected scrollbar colour.
Firefox in foreground, Qupzilla behind.
http://i.imgur.com/zSOGNLO.png

**Comment by m1ga** [comment]
and the blue highlight color should have a bigger contrast to the grey area below:
![hl](https://cloud.githubusercontent.com/assets/4334997/9832044/ef6e47ce-596e-11e5-8b79-d2785323a5d2.png)
