### ISSUE TITLE
Latest breeze-gtk produces incorrect scroll bars and other UI elements in Debian testing  / KDE Plasma 5.4

### ISSUE THREAD

**Issue by shmerl** [dirruk1/gnome-breeze#29]
I just downloaded master branch for breeze-gtk (both 2 and 3), and put them in $HOME/.local/share/themes.

I selected them as GTK themes in KDE System Settings (current Debian testing, Plasma 5.4). And that's what I get in Firefox now:
![breeze-gtk-bug](https://cloud.githubusercontent.com/assets/310927/9835296/2c462250-59b2-11e5-9cbd-199335d9ec7a.jpg)

Similar incorrect UI elements can be seen in various menus and dialogs. This happens with all GTK applications, not just with Firefox.

**Comment by rumangerst** [comment]
Did you install gtk2-engines-pixbuf ? Had the same problem and installing this package fixed it.

**Comment by shmerl** [comment]
Thanks! That helped indeed. Is that some library package which is used by similar themes?
