### ISSUE TITLE
No black borders around menus for GTK2 theme

### ISSUE THREAD

**Issue by Steinhagen** [dirruk1/gnome-breeze#3]
HexChat: (GTK2)
![gtk2appborder](https://cloud.githubusercontent.com/assets/4029937/7920994/17212422-08ab-11e5-8225-bf4100fb2eeb.png)
Gwenview: (Qt5)
![qt5appborder](https://cloud.githubusercontent.com/assets/4029937/7920993/17200bf0-08ab-11e5-8236-05e00756e1cc.png)

Also, the color of GTK2 menus is grey instead of white.

**Comment by dirruk1** [comment]
Can you try this version https://github.com/dirruk1/gnome-breeze/tree/gtk2-dark and tell me if the borders are there

**Comment by Steinhagen** [comment]
I've tried it and it works! Thanks a lot!
![gtk2border](https://cloud.githubusercontent.com/assets/4029937/7967409/923be4ca-0a32-11e5-9181-be914ea6843b.png)
