### ISSUE TITLE
Scrollbar colors of breeze-gtk in Firefox don't match KDE/qt theme

### ISSUE THREAD

**Issue by shmerl** [dirruk1/gnome-breeze#30]
In my case (Debian testing, KDE Plasma 5.4), scrollbars in Firefox have slightly different color from Qt applications. In some other GTK applications they are OK (for example in Geany).

Firefox scrollbar:
![scrollbar-gtk](https://cloud.githubusercontent.com/assets/310927/9838139/bcff0bec-5a23-11e5-8542-946ca2a48fcd.png)

Konsole scrollbar:
![scrollbar-qt](https://cloud.githubusercontent.com/assets/310927/9838140/c3cca3da-5a23-11e5-85c9-fe1f5a08b305.png)

Switching "Apply colors to non-Qt applications" on or off doesn't affect this issue.

**Comment by FLHerne** [comment]
Duplicate of one I [already filed](https://github.com/dirruk1/gnome-breeze/issues/26).

**Comment by shmerl** [comment]
OK, closing it.
