### ISSUE TITLE
Undraggable area in the scrollbar margins

### ISSUE THREAD

**Issue by shmerl** [dirruk1/gnome-breeze#31]
breeze-gtk theme (I tested it with GTK2 one in Firefox) doesn't allow one to drag the scorllbar when mouse pointer is on the margin, left or right of the actual scrollbar UI element (see red marks in the example below):
![scrollbar-bug](https://cloud.githubusercontent.com/assets/310927/9911687/4d2f81c0-5c71-11e5-847f-e837b0eec7ab.png)

That makes it quite annoying when you don't hover exactly above it and can't scroll. In comparison, in Qt Breeze theme, one can scroll even when the mouse is above the margin.

**Comment by shmerl** [comment]
Is anyone still working on this?

**Comment by ghost** [comment]
Yes, we've all just been very busy with other things lately.

Part of the problem with expanding the grabbable area beyond the scrollbar is that we generate the assets to use the least amount of space needed and expanding it would require transparent boundaries in the source SVGs. It would also expand scrollbar areas in certain applications that provide separate padding, and we'll have to handle this correctly in the future with color generation scripts.

So yeah, I agree it would be preferable, but there are a few things standing in the way. Ultimately, I think it would be best for the empty space to be grabbable for usability. I'll try to mitigate the negative side-effects in those niche apps. We're planning to refactor the GTK 3 code and polish everything up soon, so hopefully I can tackle it when that happens.

**Comment by shmerl** [comment]
Thanks for the update!

**Comment by ghost** [comment]
This is now fixed in the upstream-polish branch, which will likely become master fairly soon. Keeping the issue open until then, of course.

**Comment by shmerl** [comment]
This works fine now in master as well.
