### ISSUE TITLE
Items disappear in context menu on mouse hover in Chrome

### ISSUE THREAD

**Issue by sudhirkhanger** [dirruk1/gnome-breeze#38]
Items in context menu disappear on mouse hover. This problem is discussed at [here](https://productforums.google.com/forum/#!topic/chrome/u_v6bET8o8o), [here](https://code.google.com/p/chromium/issues/detail?id=378090) and [here](https://code.google.com/p/chromium/issues/detail?can=2&start=0&num=100&q=white%20on%20white%20menu&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=371028).

![menu_white_on_white2](https://cloud.githubusercontent.com/assets/841656/10858090/606b0e56-7f78-11e5-998f-4cbf98827294.png)

**Comment by shmerl** [comment]
You can add that it happens in Chrome. I don't see such problem in Firefox for example.

**Comment by ghost** [comment]
I can't reproduce this bug in Google Chrome 46. Are you using a different version, @sudhirkhanger?

**Comment by sudhirkhanger** [comment]
I am using Chrome version 46.0.2490.80 (64-bit). I am not sure what happened I can't reproduce it anymore.
