### ISSUE TITLE
Where to report bugs for breeze-gtk?

### ISSUE THREAD

**Issue by shmerl** [dirruk1/gnome-breeze#45]
I see now that breeze-gtk is integrated in KDE codebase, KDE bug tracker supports filing bugs for it:

https://bugs.kde.org/buglist.cgi?component=gtk%20theme&list_id=1318150&product=Breeze&query_format=advanced

Is KDE bugzilla now the preferred place, or this Github repo should still be used? It's better to have one place to avoid confusion (if KDE bug tracker is preferred, may be it's good to point out that in this repo, or even make it read only for issues?).

**Comment by ghost** [comment]
You'll want to report on KDE's bugtracker, but you may want to hold off until we can merge this repo's final update into Plasma (no use in re-reporting bugs that are fixed here). Not sure when that will happen as I'm unavailable to do it for the time being, but I imagine it will be in one of the bugfix updates, then you can have at it.

Not sure what will happen to this repo- we may transfer the bugs and close all of them here, or simply make this repo a clone of the KDE one. Or, as usually happens, this repo may simply do nothing from now on.

**Comment by stevenroose** [comment]
How will we have to migrate from a manual installation using this repo to
the one in Plasma?

**Comment by ghost** [comment]
@stevenroose It should be a package named 'breeze-gtk' in any distro that carries Plasma 5.5.
