### ISSUE TITLE
Menus in nautilus header-bar are transparent

### ISSUE THREAD

**Issue by purejava** [dirruk1/gnome-breeze#59]
**!WOW! - thank you for this cool theme - it's awesome!**

Minor bug: the menus in the nautilus header-bar are transparent.
Arch linux, nautilus 3.20.1-1, gnome-breeze theme from master from today.

Thanks,

![bildschirmfoto vom 2016-05-22 19-53-04](https://cloud.githubusercontent.com/assets/1822238/15455576/9dc8750a-2058-11e6-9f5a-e3040af31762.png)

**Comment by ghost** [comment]
This is currently fixed in the color-effects branch which should be merged into master sometime soon, at which point we'll close this issue.

EDIT: Ah, silly me- looks like I've been out of the loop.

**Comment by dirruk1** [comment]
It is already merged

**Comment by purejava** [comment]
That was quick! :) :+1: 
Thank you.

Also works with latest gtk3-3.20.5-2 - everything fine now for me.
