### ISSUE TITLE
Tab bar color on chrome/chromium

### ISSUE THREAD

**Issue by tago73** [dirruk1/gnome-breeze#60]
Hi, thanks for this great work... the last version is perfect for libreoffice, inkscape and all other gtk2 app but for chrome there's a issue on tab bar color...

**Comment by dirruk1** [comment]
could you be a bit more specific? Maybe a screenshot?

**Comment by tago73** [comment]
Hi, see the attached screenshot..

![with focus](https://cloud.githubusercontent.com/assets/19559140/15541266/05f5fd34-228c-11e6-91f3-189176a3e4f3.png)
![without focus](https://cloud.githubusercontent.com/assets/19559140/15541267/05fbd8c6-228c-11e6-9bcf-164cb2a53b88.png)

2016-05-25 12:08 GMT+02:00 Henk de Vries notifications@github.com:

**Comment by tago73** [comment]
Great! Now works well... :)
